name: Build libsimple.so for armeabi-v7a

on:
  workflow_dispatch:     # 支持手动触发
  push:                  # 每次提交代码时自动运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. 拉取最新源码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 安装和配置 Android NDK
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26d      # 选择稳定的NDK版本

    # 3. 执行编译
    - name: Build with NDK
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/${{ steps.setup-ndk.outputs.ndk-version }}/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=armeabi-v7a \      # 指定为目标架构
              -DANDROID_PLATFORM=android-26 \
              -DBUILD_SQLITE3=OFF \
              -DCMAKE_BUILD_TYPE=Release ..
        make

    # 4. 保存编译成果
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: libsimple-android-armeabi-v7a
        path: build/libsimple.so
